### ISSUE TITLE
Linear regression class accesses intercept_stderror from scipy (py 3.6 <= problems)

### ISSUE THREAD

**Issue by wptmdoorn** [wptmdoorn/methcomp#15] opened 2021-05-23 08:25 UTC
The new Linear regression class uses `intercept_stderr` from scipy.stats which was implemented in their v1.6.0 release (https://github.com/scipy/scipy/pull/12983). The v1.6.0 release is unfortunately not available for Python 3.6 or lower - which means we either need to drop Python 3.6 support, or create some work arounds designed for Python 3.6.

Thoughts? @thomasburgess 

Also see: 
https://travis-ci.org/github/wptmdoorn/methcomp/jobs/772064968
https://travis-ci.org/github/wptmdoorn/methcomp/jobs/772064969

**Comment by thomasburgess** [comment] 2021-05-23 10:57
I looked into calculating it myself, but then we have to reimplement the while regression which seems a little silly. Statsmodels causes warnings with python 3.8+ which is why I was thinking of getting rid of it. I feel perhaps it is not unreasonable to keep up with the minimal versions required by scipy.

**Comment by thomasburgess** [comment] 2021-05-23 12:16
On the other hand, if this is all that keeps us from 3.6:

```python

intercept_stderr = stderr * np.sqrt(np.var(x) + x.mean()**2)
```

I'll give it a try

**Comment by thomasburgess** [comment] 2021-05-23 12:34
Ok this is now in branch `feature/precommit` - I am not 100% it works, and test will require a mock - please try it
```
        # Hack to support scipy < 1.60
        if "intercept_stderr" not in result:
            result["intercept_stderr"] = result["stderr"] * np.sqrt(
                np.var(self.method1) + self.method1.mean() ** 2
            )
```

**Comment by wptmdoorn** [comment] 2021-05-23 12:58
Thanks, I see you kind of adopted the scipy.stats implementation of the `intercept_stderr`. I will test it and see if it returns the same results. I think this is an appropriate solution for the solution, as dropping <py3.7 support already is probably a bit too early. 

Will come back to you.

**Comment by thomasburgess** [comment] 2021-05-23 13:49
As the calculation was so simple, I figure it is ok to borrow one line from scipy... for bigger chunks I wouldn't advise doing this

**Comment by wptmdoorn** [comment] 2021-05-24 10:53
Yes, it looks good. I will review pre-commit branch now and if we merge it we can close this issue.

**Comment by thomasburgess** [comment] 2021-05-24 10:54
Note: i had to add pyproject.toml, not sure how that interacts with setup.py, better check dist works as intended...

**Comment by thomasburgess** [comment] 2021-05-27 09:05
Ok, with travis finally happy, I guess we can close this guy now

**Closed** 2021-05-27 09:37 UTC
